import { getMessages } from 'next-intl/server';
import "./globals.css";
import { ThemeContextProvider } from '@/contexts/ThemeContext';
import ScrollToTopButton from "@/components/Effects/ScrollToTopButton";
import FloatingButton from "@/components/Effects/FloatingButton";
import { NextIntlClientProvider } from 'next-intl';

export const generateMetadata = async ({ params: { locale } }: { params: { locale: string } }) => ({
  title: `Create Next App - ${locale}`,
  description: `Generated by create next app in ${locale}`,
});

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages({ locale }); // Chỉnh sửa ở đây

  return (
    <html lang={locale}>
      <body className="bg-white dark:bg-[#0d2438] text-gray-700 dark:text-gray-100">
        <NextIntlClientProvider messages={messages}>
          <ThemeContextProvider>
            {children}
            <ScrollToTopButton />
            <FloatingButton />
          </ThemeContextProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
