import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {unstable_setRequestLocale} from 'next-intl/server';
import type { Metadata } from "next";
import "./globals.css";
import { ThemeContextProvider } from '@/contexts/ThemeContext';
import ScrollToTopButton from "@/components/Effects/ScrollToTopButton";
import FloatingButton from "@/components/Effects/FloatingButton";
export default async function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  // Providing all messages to the client
  // side is the easiest way to get started
  unstable_setRequestLocale(locale);
  const messages = await getMessages();
 

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
        <ThemeContextProvider>

          {children}
          <ScrollToTopButton />
          <FloatingButton />
        </ThemeContextProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}